#!/bin/sh
xrdb -remove
xrdb < $HOME/git/xresources/overrides
xrdb < $HOME/git/xresources/current
urxvt -depth 32 -cr '#995533'  -sh 16 -bg rgba:1111/1111/1111/c000 +sb -fn '-xos4-terminesspowerline-medium-r-normal--16-*-*-*-c-*-*-*' -fb '-xos4-terminesspowerline-medium-r-normal--16-*-*-*-c-*-*-*'

