#!/bin/bash

set -x

font="-*-terminesspowerline-medium-*-*-*-16-*-*-*-*-*-iso10646-1"

# reload Xresources settings
xrdb -remove
cat $HOME/git/xtheme/xresources/current $HOME/git/xtheme/xresources/overrides | xrdb

# start terminal emulator
# -sh: shading
# -fn: normal font
# -fb: bold font
urxvt -depth 32 -cr '#bb3333' -sh 16 -bg rgba:1111/1111/1111/c000 +sb -fg '#cccccc' -fn "$font" -fb "$font"

